### ISSUE TITLE
cannot run sitl on rasbian as it's an x86 elf

### ISSUE THREAD

**Issue by wx4cb** [dronekit/dronekit-python#1014]
title says it all, trying to run on a raspberry pi as the onboard computer will be a pi zero

running the first script int he quick start guide [https://dronekit-python.readthedocs.io/en/latest/guide/quick_start.html] gives me this: 
```
charlesb@TalonFC:/usr/src $ python dronekit-tst.py
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Traceback (most recent call last):
  File "dronekit-tst.py", line 4, in <module>
    sitl = dronekit_sitl.start_default()
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 462, in start_default
    sitl.launch(sitl_args, await_ready=True, restart=True)
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 251, in launch
    caps = ArdupilotCapabilities(self.path)
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 160, in __init__
    process = subprocess.Popen([path, '--help'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
```

As ytou can see it's in the wrong binary format.

Running "file" on it tells me that it's compiled for x86_64 which is wrong as the pi is arm based. how can i get around this?

```
charlesb@TalonFC:~/.dronekit/sitl/copter-3.3 $ file apm
apm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=28117a45d9f13887fcd710969a1d55c896fcd6f8, stripped
charlesb@TalonFC:~/.dronekit/sitl/copter-3.3 $ uname -a
Linux TalonFC 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux

```

**Comment by mustafa-gokce** [comment]
There are no binaries for arm architecture, you have to compile yourself.
