### ISSUE TITLE
Error Running Example - guided_set_speed_yaw 

### ISSUE THREAD

**Issue by nitin-rakheja** [dronekit/dronekit-python#1027]
I am facing teething issues in running the examples of dronekit-python. May I request you to help me by advising the error. Alternatively, you could guide me to some forum where I could seek such assistance from experts like you. 
Thanks,
Nitin

C:\Users\Nitin Rakheja\dronekit-python\examples\guided_set_speed_yaw>python guided_set_speed_yaw.py --connect 127.0.0.1:14550
Connecting to vehicle on: 127.0.0.1:14550
CRITICAL:autopilot:APM:Copter V3.3 (d6053245)
CRITICAL:autopilot:Frame: QUAD
Basic pre-arm checks
Arming motors
Waiting for arming...
Waiting for arming...
Waiting for arming...
Waiting for arming...
ERROR:autopilot:ARMING MOTORS
CRITICAL:autopilot:GROUND START
Waiting for arming...
WARNING:dronekit:Link timeout, no heartbeat in last 5 seconds
CRITICAL:autopilot:Initialising APM...
Waiting for arming...
Taking off!
Altitude: 0.0
Altitude: 0.0
Altitude: 0.35
Altitude: 1.75
Altitude: 3.47
Altitude: 4.48
Altitude: 4.77
Reached target altitude
TRIANGLE path using standard Vehicle.simple_goto()
Set groundspeed to 5m/s.
Position North 80 West 50
Distance to target: 100.792763380213
Distance to target: 100.11398742575105
Distance to target: 96.186820284368
Distance to target: 89.04249381271293
Distance to target: 80.96699334302501
Distance to target: 71.80281739732008
Distance to target: 62.20222994794249
Distance to target: 52.32675641281927
Distance to target: 41.019893134539345
Distance to target: 30.872658578432933
Distance to target: 20.713088476847503
Distance to target: 10.694598623783632
Distance to target: 2.7953944634087287
Distance to target: 1.0763816038298724
Distance to target: 1.4883368960892098
Distance to target: 1.1135299392032731
Distance to target: 0.7786369540566108
Reached target
Position North 0 East 100
Distance to target: 122.62321081285523
Distance to target: 121.45467490708386
Distance to target: 116.89123666216402
Distance to target: 108.45236700787655
Distance to target: 98.967827079484
Distance to target: 88.2811626103933
Distance to target: 75.61302611566751
Distance to target: 65.47191579045955
Distance to target: 52.25845839082774
Distance to target: 40.47003222455401
Distance to target: 28.570512514485984
Distance to target: 15.312673607091877
Distance to target: 5.3177053784447
Distance to target: 0.22284337996149609
Reached target
Position North -80 West 50
Distance to target: 100.79243113691925
Distance to target: 100.75280370293063
Distance to target: 97.93607804736676
Distance to target: 91.17400510958724
Distance to target: 83.19148498475043
...
Distance to target: 11.943533952684488
Distance to target: 2.8503279238857724
Distance to target: 0.5745724039716981
Reached target
TRIANGLE path using standard SET_POSITION_TARGET_GLOBAL_INT message and with varying speed.
Position South 100 West 130
Set groundspeed to 5m/s.
SET_POSITION_TARGET_GLOBAL_INT {time_boot_ms : 0, target_system : 0, target_component : 0, coordinate_frame : 6, type_mask : 4088, lat_int : -353641616.1528412, lon_int : 1491637872.8132381, alt : 4.75, vx : 0, vy : 0, vz : 0, afx : 0, afy : 0, afz : 0, yaw : 0, yaw_rate : 0}
Traceback (most recent call last):
File "guided_set_speed_yaw.py", line 454, in <module>
goto(-100, -130, goto_position_target_global_int)
File "guided_set_speed_yaw.py", line 313, in goto
gotoFunction(targetLocation)
File "guided_set_speed_yaw.py", line 265, in goto_position_target_global_int
vehicle.send_mavlink(msg)
File "C:\Users\Nitin Rakheja\AppData\Local\Programs\Python\Python38\lib\site-packages\dronekit__init__.py", line 2215, in send_mavlink
self._master.mav.send(message)
File "C:\Users\Nitin Rakheja\AppData\Local\Programs\Python\Python38\lib\site-packages\dronekit\mavlink.py", line 146, in newsendfn
return sendfn(mavmsg, args, *kwargs)
File "C:\Users\Nitin Rakheja\AppData\Local\Programs\Python\Python38\lib\site-packages\pymavlink\dialects\v10\ardupilotmega.py", line 12208, in send
buf = mavmsg.pack(self, force_mavlink1=force_mavlink1)
File "C:\Users\Nitin Rakheja\AppData\Local\Programs\Python\Python38\lib\site-packages\pymavlink\dialects\v10\ardupilotmega.py", line 9211, in pack
return MAVLink_message.pack(self, mav, 5, struct.pack('<IiifffffffffHBBB', self.time_boot_ms, self.lat_int, self.lon_int, self.alt, self.vx, self.vy, self.vz, self.afx, self.afy, self.afz, self.yaw, self.yaw_rate, self.type_mask, self.target_system, self.target_component, self.coordinate_frame), force_mavlink1=force_mavlink1)
**struct.error: required argument is not an integer**

**Comment by nitin-rakheja** [comment]
changed the parameters to int() and working fine
