### ISSUE TITLE
Can't connect pixhawk via 3DR telemetry( serial ) using dronekit

### ISSUE THREAD

**Issue by amgaber95** [dronekit/dronekit-python#1055]
I am a newbie to dronekit. I have been trying to establish a connection between Pixhawk and my python script, however, it gives me this error:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Abdelrahman\.spyder-py3\temp.py", line 209, in loop
    self.connect_my_copter()
  File "C:\Users\Abdelrahman\.spyder-py3\temp.py", line 270, in connect_my_copter
    self.vehicle = connect(self.connection_string,baud=57600, wait_ready=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dronekit\__init__.py", line 3170, in connect
    vehicle.wait_ready(still_waiting_interval=still_waiting_interval,
  File "C:\ProgramData\Anaconda3\lib\site-packages\dronekit\__init__.py", line 2374, in wait_ready
    raise TimeoutError('wait_ready experienced a timeout after %s seconds.' %
dronekit.TimeoutError: wait_ready experienced a timeout after 30 seconds.

timeout error

I am using port "COM3" that I connect my 3dr telemetry part to. 

using this vehicle = connect(connection_string,baud=57600, wait_ready=True), although I managed to connect it through USB cable connect to Pixhawk and also successfully connect to Pixhawk and it works fine with a mission planner. Please help me, why I can't connect to the drone using 3Dr telemetry.

**Comment by amgaber95** [comment]
Please any one answer me>. I really need your help
