### ISSUE TITLE
dronekit.APIException: Timeout in initializing connection.

### ISSUE THREAD

**Issue by darpant-289** [dronekit/dronekit-python#1067]
***WARNING:dronekit:Link timeout, no heartbeat in last 5 seconds
ERROR:dronekit.mavlink:Exception in MAVLink input loop
Traceback (most recent call last):
  File "/home/ips/drone/venv/local/lib/python2.7/site-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/home/ips/drone/venv/local/lib/python2.7/site-packages/dronekit/__init__.py", line 1371, in listener
    self._heartbeat_error)
APIException: No heartbeat in 30 seconds, aborting.
Traceback (most recent call last):
  File "d1.py", line 16, in <module>
    vehicle = connectMyCopter()
  File "d1.py", line 13, in connectMyCopter
    vehicle = connect(connection_string, wait_ready=True)
  File "/home/ips/drone/venv/local/lib/python2.7/site-packages/dronekit/__init__.py", line 3166, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "/home/ips/drone/venv/local/lib/python2.7/site-packages/dronekit/__init__.py", line 2275, in initialize
    raise APIException('Timeout in initializing connection.')
dronekit.APIException: Timeout in initializing connection.

**Comment by nandard** [comment]
HI, i'm facing the same problem just like you said. I'm very glad to hear the solustion. Thanks

**Comment by harmor123** [comment]
me too!
