### ISSUE TITLE
error on trying to run drone await set(types) invalid syntax error

### ISSUE THREAD

**Issue by prashanthravi19** [dronekit/dronekit-python#1069]
i get an error while trying to run drone delivery.py how can the bug be resolved?
 await = set(types)
          ^
SyntaxError: invalid syntax
full stack trace
Traceback (most recent call last):
  File "drone_delivery.py", line 18, in <module>
    from dronekit import connect, VehicleMode, LocationGlobal, LocationGlobalRelative
  File "C:\Users\Prashanth\AppData\Local\Programs\Python\Python38\lib\site-packages\dronekit\__init__.py", line 2192
    await = set(types)
          ^
SyntaxError: invalid syntax

**Comment by 4NTH3L1OS** [comment]
I think you should use Python 2.7 to run your code. Can you try it? There is a some syntax differences between Python 3.x and Python 2.x. The error may be caused by this situation.

**Comment by prashanthravi19** [comment]
thank u i ve made changes the app is running but when i run dronekit delivery it gets stuck on polled  mode guided

**Comment by jinkalr-itpath** [comment]
I want to connect DJI drone, can I use droneKit API? its urgent please
