### ISSUE TITLE
hello.py not working

### ISSUE THREAD

**Issue by lweingart** [dronekit/dronekit-python#1085]
Dear team,

I am absolutely new to dronekit and my goal is to have a jetson nano giving commands to a drone via pixhawk.
Therefore I decided to start with the beginning, which is the hello.py.

Fortunately for my, the drone is actually a blimp, and I will mostly have to give instructions to turn left or right and not have to worry too much about hovering and altitude changes, or take offs and landings.

I'm using python3 and ubuntu 18.04 in installed on my jetson nano.

Here is what I get when trying to run hello.py (obviously after the few modifications for python3)

```
$ python hello.py
Start simulator (SITL)
Starting copter simulator (SITL)
Downloading SITL from http://dronekit-assets.s3.amazonaws.com/sitl/copter/sitl-linux-copter-3.3.tar.gz
Download Complete.
Payload Extracted.
Ready to boot.
Traceback (most recent call last):
  File "hello-drone.py", line 3, in <module>
    sitl = dronekit_sitl.start_default()
  File "/home/jetson/.virtualenvs/droning_micr/lib/python3.6/site-packages/dronekit_sitl/__init__.py", line 462, in start_default
    sitl.launch(sitl_args, await_ready=True, restart=True)
  File "/home/jetson/.virtualenvs/droning_micr/lib/python3.6/site-packages/dronekit_sitl/__init__.py", line 251, in launch
    caps = ArdupilotCapabilities(self.path)
  File "/home/jetson/.virtualenvs/droning_micr/lib/python3.6/site-packages/dronekit_sitl/__init__.py", line 160, in __init__
    process = subprocess.Popen([path, '--help'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/jetson/.dronekit/sitl/copter-3.3/apm'
```

As it seems that the documentation has not been been updated in quite some time (it says for instance that python 3 is not supported, but I found [here](https://github.com/dronekit/dronekit-python/issues/1001) that it is), I was wondering how much I should trust what I find in it, or if I should skip some parts of it.

Any help in my new journey would be very much appreciated.

Cheers,
Laurent

**Comment by lweingart** [comment]
Hi again,

After some digging I found out that dronekit-sitl doesn't work on arm.
Case closed, I'll do the development on an ubuntu x86

Thank you guys
Laurent
