### ISSUE TITLE
 Waiting for arming... ERROR:autopilot:ARMING MOTORS

### ISSUE THREAD

**Issue by danammeansbear** [dronekit/dronekit-python#1087]
runfile('C:/Users/fahre/Desktop/GuiltySparkProject/KITTI-distance-estimation-master/dronemission.py', wdir='C:/Users/fahre/Desktop/GuiltySparkProject/KITTI-distance-estimation-master')
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Connecting to vehicle on: tcp:127.0.0.1:5780
CRITICAL:autopilot:APM:Copter V3.3 (d6053245)
CRITICAL:autopilot:Frame: QUAD
Create a new mission (for current location)
 Clear any existing commands
 Define/add new commands.
 Upload new commands to vehicle
CRITICAL:autopilot:flight plan received
Basic pre-arm checks
Arming motors
 Waiting for arming...
 Waiting for arming...
 Waiting for arming...
 Waiting for arming...
ERROR:autopilot:ARMING MOTORS
CRITICAL:autopilot:GROUND START
 Waiting for arming...
WARNING:dronekit:Link timeout, no heartbeat in last 5 seconds
CRITICAL:autopilot:Initialising APM...
Taking off!
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.01
 Altitude:  0.02
 Altitude:  0.02
ERROR:autopilot:DISARMING MOTORS
 Altitude:  0.02
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  0.0
 Altitude:  -0.01
 Altitude:  -0.01
 Altitude:  -0.01
 Altitude:  -0.01
 Altitude:  -0.01
 Altitude:  -0.01
 Altitude:  -0.01
Traceback (most recent call last):

  File "C:\Users\fahre\Desktop\GuiltySparkProject\KITTI-distance-estimation-master\dronemission.py", line 168, in <module>
    arm_and_takeoff(10)

  File "C:\Users\fahre\Desktop\GuiltySparkProject\KITTI-distance-estimation-master\dronemission.py", line 160, in arm_and_takeoff
    time.sleep(1)

KeyboardInterrupt

**Comment by danammeansbear** [comment]
I have tried pip uninstall pymavlink and reinstall pymavlink2.4.8 instead of 2.4.14 or something and it doesnt work either.

**Comment by danammeansbear** [comment]
https://github.com/dronekit/dronekit-python/issues/1083#issuecomment-761582531
