### ISSUE TITLE
Dronekit 2.9.2 experience sharing

### ISSUE THREAD

**Issue by Jai-GAY** [dronekit/dronekit-python#1139]
[Name: dronekit Version: **2.9.2**](https://github.com/dronekit/dronekit-python/releases/tag/v2.9.2)
Name: pyserial Version: 3.4
Python 2.7.16

[SERIAL1_BAUD,921 #connect to companion computer](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/)
SERIAL1_OPTIONS,0
SERIAL1_PROTOCOL,2
[SERIAL2_BAUD,921 #connect to Herelink](https://docs.cubepilot.org/user-guides/herelink/herelink-overview)
SERIAL2_OPTIONS,0
**SERIAL2_PROTOCOL,2**

for the above [Ardupilot copter 4.1.0](https://firmware.ardupilot.org/Copter/stable-4.1.0/), python code will encounter the following issue but not **[MAVProxy Version: 1.8.46](https://ardupilot.org/mavproxy/)**. To overcome this I have to set SERIAL2_PROTOCOL,-1

ERROR:dronekit:Exception in message handler for HEARTBEAT
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dronekit/__init__.py", line 1531, in notify_message_listeners
    fn(self, name, msg)
  File "/usr/local/lib/python2.7/dist-packages/dronekit/__init__.py", line 1223, in listener
    raise APIException("mode (%s, %s) not available on mavlink definition" % (m.custom_mode, m.base_mode))
APIException: mode (33554830, 0) not available on mavlink definition

**Comment by Jai-GAY** [comment]
I got the [answer]([Connect to drone via HereLink and Drone-kit Python](https://discuss.cubepilot.org/t/connect-to-drone-via-herelink-and-drone-kit-python/7887)).
