### ISSUE TITLE
I'm having this issue while running any example in the SITL.

### ISSUE THREAD

**Issue by septi00** [dronekit/dronekit-python#1193]
File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_common.py", line 480, in wrapper
    raise raise_from(err, None)
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in raise_from
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_common.py", line 478, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_psosx.py", line 373, in _get_kinfo_proc
    ret = cext.proc_kinfo_oneshot(self.pid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ProcessLookupError: [Errno 3] assume no such process (originated from sysctl(kinfo_proc), len == 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/__init__.py", line 719, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_psosx.py", line 346, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_psosx.py", line 471, in create_time
    return self._get_kinfo_proc()[kinfo_proc_map['ctime']]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/_psosx.py", line 351, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=23916)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/pythonProject/venv/dronekit-python/examples/set_attitude_target/set_attitude_target.py", line 190, in <module>
    sitl.stop()
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/dronekit_sitl/__init__.py", line 388, in stop
    kill(self.p.pid)
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/dronekit_sitl/__init__.py", line 33, in kill
    process = psutil.Process(proc_pid)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/Users/user/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=23916)

This exact one occure while runnig the:  set_attitude_target.py example

**Comment by hamishwillee** [comment]
This could be a SITL and Python3 issue. Do you have the same error if you connect to a normal simulator instance?

**Comment by TongBingda** [comment]
I think this may be due to a problem with your Python environment, have you tried Python 3.8 and below and tried to run your py file directly?
