### ISSUE TITLE
first script attempt error

### ISSUE THREAD

**Issue by wangyz9595** [dronekit/dronekit-python#1231]
when i run first script( in quick start) on my PC(windows11 )  using python3.13, i have stucked with this problem:

(dronekit) D:\Space\python\venv\dronekit\Scripts>python D:\Space\python\code\hello.py
Start simulator (SITL)
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Traceback (most recent call last):
  File "D:\Space\python\code\hello.py", line 8, in <module>
    from dronekit import connect, VehicleMode
  File "D:\Space\python\venv\dronekit\Lib\site-packages\dronekit\__init__.py", line 2689, in <module>
    class Parameters(collections.MutableMapping, HasObservers):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'

so how can i resolve it!

**Comment by wangyz9595** [comment]
I downgrade Python to version 3.8.10,and then it worked!
