### ISSUE TITLE
DroneKit / MAVProxy not respecting the windows path inside quote marks

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#291]
The following start command fails:

```
api start  “C:\Program Files (x86)\MAVProxy\examples\vehicle_state\vehicle_state.py"
```
It returns the following error:
```
STABILIZE> api start "C:\Program Files (x86)\MAVProxy\examples\vehicle_state\vehicle_state.py"

STABILIZE> Exception in APIThread-0: [Errno 2] No such file or directory: '"C:\\Program'

Traceback (most recent call last):

  File "C:\PROGRA~2\MAVProxy\droneapi\module\api.py", line 333, in run

STABILIZE>    self.fn()

  File "C:\PROGRA~2\MAVProxy\droneapi\module\api.py", line 625, in <lambda>

    APIThread(self, lambda: execfile(args[1], g), args[1])

IOError: [Errno 2] No such file or directory: '"C:\\Program'
```

Mavproxy or dronekit does not interpret the directory  correctly. Tried everything I could with other path syntaxes without success.

This originates here: https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues/128#issuecomment-131135888 

@mrpollo I have verified issue with 1.5 Windows Installer and with a normal Python installation from PIP.

**Comment by hamishwillee** [comment]
This has been fixed in latest MAVProxy.
