### ISSUE TITLE
DKPY2 vehicle_state.py has no attribute 'wp_op'

### ISSUE THREAD

**Issue by hamishwillee** [dronekit/dronekit-python#316]
On the new "master" DKPY2 branch ran vehicle_state.py. It failed waiting on commands to download:
```
Get home location
Traceback (most recent call last):
  File "D:\deleteme\dronekit-python\examples\vehicle_state\vehicle_state.py", line 86, in <module>
    cmds.download()
  File "build\bdist.win-amd64\egg\droneapi\module\api.py", line 56, in download
  File "build\bdist.win-amd64\egg\droneapi\module\api.py", line 63, in wait_valid
AttributeError: MPFakeState instance has no attribute 'wp_op'
```

**Comment by tcr3dr** [comment]
This is fixed as of https://github.com/dronekit/dronekit-python/pull/330 .
