### ISSUE TITLE
Thread exceptions after multiple script executions

### ISSUE THREAD

**Issue by dharo** [dronekit/dronekit-python#572]
When launching a script that initializes a vehicle and connects, if that script is closed, regardless if  vehicle.close() was inserted at the end, the next time the script is launched this error returns at some point during the script termination:

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
  File "/usr/local/lib/python2.7/dist-packages/dronekit/mavlink.py", line 84, in mavlink_thread
```

To resolve this issue, I must restart the Raspberry Pi I'm using to communicate with my APM.

I'm curious if there is an error on my part, or if anyone else is encountering this issue.

**Comment by hamishwillee** [comment]
Thanks for posting. FYI, yes, I have seen similar issues.
