### ISSUE TITLE
Python 3 syntax does not support expressions in mavlink.py

### ISSUE THREAD

**Issue by SLongofono** [dronekit/dronekit-python#733]
See the traceback below, the line 240 tries to print the exception details using e.message, but this syntax is not valid in Python 3.

I can push a fix or a pull request if necessary, dropping ".message" should work as far as I can tell.

```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/usr/local/lib/python3.5/dist-packages/dronekit/__init__.py", line 1346, in listener
    self._heartbeat_error)
dronekit.APIException: No heartbeat in 30 seconds, aborting.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dronekit/mavlink.py", line 240, in mavlink_thread_in
    errprinter('>>> ' + str(e.message))
AttributeError: 'APIException' object has no attribute 'message'
 ```

**Comment by SLongofono** [comment]
Closing this, apparently the pip3 module for dronekit does not include [this fix](https://github.com/dronekit/dronekit-python/commit/5d2614f79092cc3ea03062a084579eb16577cd22) for the bug.
