### ISSUE TITLE
Dronekit issue on TX2 Ubuntu

### ISSUE THREAD

**Issue by rcorbari** [dronekit/dronekit-python#817]
Hello,

I'm going to setup some AI scripts on a Jetson TX2. Everything was going well until I tried hello.py script. I had an error, as well another error with the following install (which I did because I read someone solved the first issue installing Ardupilot).

The code (where you can read the error) is the following:

`nvidia@tegra-ubuntu:~$ python hello.py
Start simulator (SITL)
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    sitl = dronekit_sitl.start_default()
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 341, in start_default
    sitl.launch(sitl_args, await_ready=True, restart=True)
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 271, in launch
    p = Popen([self.path] + args, cwd=wd, shell=sys.platform == 'win32', stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
nvidia@tegra-ubuntu:~$ git clone git://github.com/ArduPilot/ardupilot.git
Cloning into 'ardupilot'...
remote: Counting objects: 215558, done.
remote: Total 215558 (delta 0), reused 0 (delta 0), pack-reused 215558
Receiving objects: 100% (215558/215558), 97.82 MiB | 7.34 MiB/s, done.
Resolving deltas: 100% (157846/157846), done.
Checking connectivity... done.
nvidia@tegra-ubuntu:~$ cd ardupilot/ArduCopter
nvidia@tegra-ubuntu:~/ardupilot/ArduCopter$ make -j4 sitl
../mk/apm.mk:25: /home/nvidia/ardupilot/modules/uavcan/libuavcan/include.mk: No such file or directory
../mk/find_tools.mk:67: *** ERROR: cannot find gawk - you may need to install GNU awk.  Stop.
nvidia@tegra-ubuntu:~/ardupilot/ArduCopter$ 
`

Could you please help me to go ahead? Thanks.

**Comment by peterbarker** [comment]
On Sun, 15 Apr 2018, Riccardo wrote:

> nvidia@tegra-ubuntu:~$ python hello.py Start simulator (SITL) Starting copter simulator (SITL) SITL already Downloaded and Extracted. Ready to boot.

Those binaries it has downloaded and extracted are x86, so they're not 
going to work on the TX2.

> Traceback (most recent call last): File "hello.py", line 3, in <module> sitl = dronekit_sitl.start_default() File
> "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 341, in start_default sitl.launch(sitl_args, await_ready=True, restart=True) File
> "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 271, in launch p = Popen([self.path] + args, cwd=wd, shell=sys.platform ==
> 'win32', stdout=PIPE, stderr=PIPE) File "/usr/lib/python2.7/subprocess.py", line 711, in __init__ errread, errwrite) File
> "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child raise child_exception OSError: [Errno 8] Exec format error nvidia@tegra-ubuntu:~$ git
> clone git://github.com/ArduPilot/ardupilot.git Cloning into 'ardupilot'... remote: Counting objects: 215558, done. remote: Total 215558 (delta 0), reused
> 0 (delta 0), pack-reused 215558 Receiving objects: 100% (215558/215558), 97.82 MiB | 7.34 MiB/s, done. Resolving deltas: 100% (157846/157846), done.
> Checking connectivity... done. nvidia@tegra-ubuntu:~$ cd ardupilot/ArduCopter nvidia@tegra-ubuntu:~/ardupilot/ArduCopter$ make -j4 sitl ../mk/apm.mk:25:
> /home/nvidia/ardupilot/modules/uavcan/libuavcan/include.mk: No such file or directory ../mk/find_tools.mk:67: *** ERROR: cannot find gawk - you may need
> to install GNU awk. Stop. nvidia@tegra-ubuntu:~/ardupilot/ArduCopter$

You'll want a full development environment; have a look at the 
install-prereqs-ubuntu.sh script in the ArduPilot source tree.
