### ISSUE TITLE
cannot connect to mission planner with python code on windows

### ISSUE THREAD

**Issue by ji5u1031** [dronekit/dronekit-python#830]
I have run SITL simulation code on mission planner and i worked.
For next step, i wished to connect my windows pc and pixhawk via mission planner and python script.
But with somewhat reason, every time i run my script, it tries to connect with the port i used on SITL simulation script, not with the port i wrote on the script, 'com4'. and I cannot find out reason why.
Is there anyone who can resolve this? I really need a help. :(

here is my python script.

from dronekit import connect, VehicleMode
import time

connection_string ='com4'
baud_rate = 57600

print(">>>> Connecting with the UAV <<<")
vehicle = connect(connection_string, wait_ready=True, baud=baud_rate)

vehicle.wait_ready('autopilot_version')
print('Autopilot version: %s'%vehicle.version)
def attitude_callback(self, attr_name, value):
    print(vehicle.attitude)

print("")
print("Adding an attitude listener")
vehicle.add_attribute_listener('attitude', attitude_callback) #-- message type, callback function
time.sleep(5)

#--- Now we print the attitude from the callback for 5 seconds, then we remove the callback
vehicle.remove_attribute_listener('attitude', attitude_callback) #(.remove)

#--- You can create a callback even with decorators, check the documentation out for more details

#---- PARAMETERS
print("Maximum Throttle: %d"%vehicle.parameters['THR_MIN']) 

#-- You can read and write the parameters
vehicle.parameters['THR_MIN'] = 50
time.sleep(1)
print("Maximum Throttle: %d"%vehicle.parameters['THR_MIN'])

#--- Now we close the simulation
vehicle.close()

print("done")

------------------------------------------------------------------------------------
and this is the result

>>>> Connecting with the UAV <<<
Connecting to vehicle on: 127.0.0.1:14551

Traceback (most recent call last):
  File "C:\Users\chnn0\pixhawk_python_test.py", line 13, in <module>
    vehicle = connect(connection_string, wait_ready=True, baud=baud_rate)
  File "C:\Python27\lib\site-packages\dronekit-2.9.1-py2.7.egg\dronekit\__init__.py", line 2835, in connect
    handler = MAVConnection(ip, baud=baud, source_system=source_system, use_native=use_native)
  File "C:\Python27\lib\site-packages\dronekit-2.9.1-py2.7.egg\dronekit\mavlink.py", line 128, in __init__
    self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system)
  File "C:\Python27\lib\site-packages\pymavlink\mavutil.py", line 1244, in mavlink_connection
    return mavserial(device, baud=baud, source_system=source_system, autoreconnect=autoreconnect, use_native=use_native)
  File "C:\Python27\lib\site-packages\pymavlink\mavutil.py", line 781, in __init__
    import serial
  File "C:\Python27\lib\site-packages\serial\__init__.py", line 12, in <module>
    standard_library.install_aliases()
  File "C:\Python27\lib\site-packages\future\standard_library\__init__.py", line 483, in install_aliases
    import test
  File "C:\Users\chnn0\test.py", line 36, in <module>
    vehicle = connect(connection_string, wait_ready=True)
  File "C:\Python27\lib\site-packages\dronekit-2.9.1-py2.7.egg\dronekit\__init__.py", line 2845, in connect
    vehicle.initialize(rate=rate, heartbeat_timeout=heartbeat_timeout)
  File "C:\Python27\lib\site-packages\dronekit-2.9.1-py2.7.egg\dronekit\__init__.py", line 2113, in initialize
    time.sleep(.1)
KeyboardInterrupt
>>> >>> Link timeout, no heartbeat in last 5 seconds
>>> No heartbeat in 30 seconds, aborting.

**Comment by ji5u1031** [comment]
I really appreciate you in advance
