### ISSUE TITLE
ImportError: No module named dronekit_sitl / dronekit

### ISSUE THREAD

**Issue by ghost** [dronekit/dronekit-python#833]
Hello! I'm trying to run python scripts on my Raspberry Pi (connected to Pixhawk) through my Ubuntu terminal. I have installed the following packages on my Ubuntu using these lines:

sudo apt-get install python-pip python-dev
pip install dronekit
pip install dronekit-sitl

as stated in this website http://python.dronekit.io/guide/quick_start.html

and I ran these in order to start the simulation:

dronekit-sitl copter-3.3 --home=30.195224,-98.107789,0,0
mavproxy.py --master tcp:127.0.0.1:5760 --out=udp:192.168.229.1:14550 --out=udp:192.168.137.200:14550

I log into the RPi using SSH:

ssh pi@192.168.137.200

But when i run this file on my RPi SSH:

python hello.py --connect "udp:192.168.137.200:14550"

I get the following error:

Start simulator (SITL)
**Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    import dronekit_sitl
ImportError: No module named dronekit_sitl**

I also used different scripts and I get the same error with dronekit...

Can anyone help me? I'm still pretty new at this. Thanks!

Here's my pip list (if it's relevant):

adium-theme-ubuntu (0.3.4)
alabaster (0.7.10)
apt-xapian-index (0.45)
argparse (1.2.1)
Babel (2.6.0)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
docutils (0.14)
droneapi (1.5.0)
dronekit (2.9.1)
dronekit-sitl (3.2.0)
duplicity (0.6.23)
empy (3.1)
funcsigs (1.0.2)
future (0.15.2)
html5lib (0.999)
httplib2 (0.8)
imagesize (1.0.0)
Jinja2 (2.10)
lockfile (0.8)
lxml (4.2.1)
MarkupSafe (1.0)
matplotlib (1.3.1)
MAVProxy (1.6.2)
mock (2.0.0)
monotonic (1.2)
nose (1.3.7)
numpy (1.8.2)
oauthlib (0.6.1)
oneconf (0.3.7)
packaging (17.1)
PAM (0.4.2)
pbr (4.0.3)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
protobuf (3.5.2.post1)
psutil (5.4.5)
pycrypto (2.6.1)
pycups (1.9.66)
Pygments (2.2.0)
pygobject (3.12.0)
pymavlink (2.0.6)
pyOpenSSL (0.13)
pyparsing (2.2.0)
pyserial (3.4)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
pyxdg (0.25)
reportlab (3.0)
requests (2.5.1)
scipy (0.13.3)
sessioninstaller (0.0.0)
setuptools (3.3)
six (1.11.0)
snowballstemmer (1.2.1)
software-center-aptd-plugins (0.0.0)
Sphinx (1.7.5)
sphinx-3dr-theme (0.4.3)
sphinxcontrib-websupport (1.0.1)
system-service (0.1.6)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
typing (3.6.4)
unity-lens-photos (1.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
wxPython (2.8.12.1)
wxPython-common (2.8.12.1)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)

**Comment by peterbarker** [comment]
On Tue, 5 Jun 2018, JeiyLP wrote:

> sudo apt-get install python-pip python-dev
> pip install dronekit
> pip install dronekit-sitl
> 
> as stated in this website http://python.dronekit.io/guide/quick_start.html

Sorry, these packages are rather out-of-date... to say the least...

Please install both of these from github.  Let me know if you need help on 
that.

**Comment by peterb0yd** [comment]
Hi @JeiyLP. I was running into this issue until I realized I had two versions of Python (2 & 3). My default version was Python 3 so pip was only installing modules for Python 3. Make sure you're installing the packages for Python 2 when using pip. 

[This StackOverflow should help.](https://stackoverflow.com/a/4910393/3386826)

**Comment by peterbarker** [comment]
On Thu, 7 Feb 2019, Radot1 wrote:

> 
> I seem to get the same error and cannot seem to fix this. Any suggestions? See error below:
>
>       "/home/pi/Desktop/otinane.py", line 1, in
>       import dronekit
>       File "/usr/lib/python3/dist-packages/thonny/backend.py", line 305, in _custom_import
>       module = self._original_import(*args, **kw)
>       ImportError: No module named 'dronekit'

python2 vs python3 issue, possibly?

try "python -m dronekit" (it should give an error - but also indicate it 
found the module)

**Comment by Turbullance** [comment]
> On Tue, 5 Jun 2018, JeiyLP wrote: sudo apt-get install python-pip python-dev pip install dronekit pip install dronekit-sitl as stated in this website http://python.dronekit.io/guide/quick_start.html
> Sorry, these packages are rather out-of-date... to say the least... Please install both of these from github. Let me know if you need help on that.

i have installed to new version of drone kit sitl which is 3.3.0 however i still receive the error 

Start simulator (SITL)
Traceback (most recent call last):
File "test2.py", line 2, in <module>
import dronekit_sitl
ImportError: No module named dronekit_sitl

**Comment by ShymkoGleb** [comment]
In the documentation they said that ARM builds like RPi are not supported by dronekit_sitl.
Checkout here https://dronekit-python.readthedocs.io/en/latest/develop/sitl_setup.html
